### ISSUE TITLE
Embed Emoji in HTML message

### ISSUE THREAD

**Issue by 360path** [mganss/EmojiAddIn#14]
Thunderbird 52.6.0

### Expected behavior

When sending emojis in an html message they are being embedded, just like in plain text messages.

### Actual behavior

When sending emojis in an html message they are sent as an image link.

### Steps to reproduce the behavior

- Compose new mail in html format.
- Insert emoji into body.
- Send message.

**Comment by mganss** [comment]
This is a feature. If you want emoji characters instead of images in an HTML message, use <kbd>Shift</kbd>-click to insert the emoji.

There are two reasons I chose to use the EmojiOne CDN instead of data: URIs for images: First, it would have increased the size of the email by a few KB for each emoji used. Second, not all MUAs (email clients) support the data protocol (e.g. Outlook).

**Comment by 360path** [comment]
I understand. Is there an option to have it insert the emoji character by default and use images on <kbd>Shift</kbd>-click?

**Comment by mganss** [comment]
Unfortunately, no.

**Comment by 360path** [comment]
ok, thanks anyway!
