### ISSUE TITLE
Emoji 1.68.4 does not work on TB 78.2.2

### ISSUE THREAD

**Issue by bagit** [mganss/EmojiAddIn#36]
### Thunderbird 78.2.2

Hello Michael,

I've updated TB to the last release 78.2.2

Emoji version **1.68.4** isn't displayed anymore (but "active" in the options).

Maybe an update is planned for your addon?

I love Emoji! 🥰
Thank you very much.

**Comment by mganss** [comment]
The add-on should automatically update to version 1.78.5 (see #34) which is compatible with TB 78. The new version is not compatible with TB 68 which is why it hadn't updated before you updated TB to 78.

I can imagine that the automatic update will only occur after a restart of TB. Have you tried that?

**Comment by bagit** [comment]
The addon update link didn't seem to work even after I restarted TB. But oops, I did it again ;) and it worked!

"Magic!" **A TB restart is not even necessary**.

I'm sincerely sorry to have bothered you with my issue, I should simply have waited a while and tried again one more time.

It's all perfect. Thank you for your quick and nice support, and thank you again for Emoji addon! 👾
